package cat.itacademy.barcelonactiva.salasderamo.ezequiel.s05.t01.n01.model;

public enum EUCountries {
        ALEMANIA, BELGICA, CROACIA, DINAMARCA, ESPAÑA, FRANCIA, IRLANDA, LETONIA, LUXEMBURGO, PAISES_BAJOS,
    SUECIA, BULGARIA, ESLOVAQUIA, ESTONIA, GRECIA, MALTA, POLONIA, REPUBLICA_CHECA, AUSTRIA, CHIPRE,
    ESLOVENIA, FINLANDIA, HUNGRIA, ITALIA, LITUANIA, PORTUGAL, RUMANIA
}
